### ISSUE TITLE
建议翻译文案的key能使用英文名称，用中文当Key，总觉得不太好

### ISSUE THREAD

**Issue by justdagege** [wuqiang1985/i18n-helper#11]

**Comment by wuqiang1985** [comment]
工具目前其实无所谓你用什么做key，可以用中文，英文，泰文等等各种都行。通过配置wrapCharacter即可，比方说wrapCharacter:[0E00-0E7F]这样可以包裹泰文。这里是通过正则来匹配。

比方说我们用中文做key对代码读取其实还是比较友好的，当然也会带来一些问题，比方说key重复需要不同的翻译，不过这个i18next命名空间也可以搞定

**Comment by justdagege** [comment]
使用过程中碰到个问题，处理后，项目代码都被webpack打包编译了，而不是仅添加目标代码，是哪里有配置错误嘛？

**Comment by wuqiang1985** [comment]
@justdagege 不太清楚你说的是啥，请详细描述下问题

**Comment by justdagege** [comment]
源代码： const a = '中文'；
期望执行后：const a = t('CHINESE');
实际执行后：var a = t('CHINESE');
大概就是这么个意思，代码同时被webpack打包了
