### ISSUE TITLE
es6 执行wrap 包裹 不需要转成 es5的代码

### ISSUE THREAD

**Issue by Yyunfan** [wuqiang1985/i18n-helper#14]
有这方面的配置么 @wuqiang1985

**Comment by wuqiang1985** [comment]
wrap本身不会对代码进行转换，你说的问题能给个例子吗

**Comment by wuqiang1985** [comment]
这里的原因应该是用了你项目的babel配置，比方说你配置了"presets": ["@babel/preset-env"]，默认会转es5
这两天会发布版本fix这个问题

**Comment by wuqiang1985** [comment]
已发布0.1.5
