### ISSUE TITLE
i18n-helper init指令不能初始化vue吗？

### ISSUE THREAD

**Issue by aboutcode** [wuqiang1985/i18n-helper#6]
D:\xxx\h5-xxx>i18n-helper init
? 请选择项目类型
>( ) js
 ( ) react
 - vue (Disabled)

为什么vue是禁用状态？

**Comment by wuqiang1985** [comment]
i18n-helper 本身跟项目是什么其实是无关的，各种国际化框架可以自选。i18n-helper init -y后去修改i18n.config.json配置就好了。
目前运行的话建议直接用i18n-helper init -y，其实就是生成各个配置文件。时间不够，后面加的参数，暂时没处理这个交互式命令，后面有时间会改下
