### ISSUE TITLE
i18n.config 配置文件exclude没有生效

### ISSUE THREAD

**Issue by rayliu0** [wuqiang1985/i18n-helper#9]
![image](https://user-images.githubusercontent.com/49531171/133572954-2e88987b-610e-4881-8dd5-87df28c8ca82.png)

**Comment by wuqiang1985** [comment]
这里是用了Prettier做格式化，用了babel作为parser，缓存typescript应该就可以了，你着急就用源码跑下，最近有点忙，我改天发布下
